#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HelloCross.Droid.Resource", IsApplication=true)]

namespace HelloCross.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int accentColor = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int accentDarkColor = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int accentLightColor = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int primaryColor = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int primaryDarkColor = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int primaryLightColor = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int primaryTextColor = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int secondaryTextColor = 2130771976;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int margin_huge = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int margin_large = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int margin_medium = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int margin_small = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int margin_tiny = 2130837508;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int ic_launcher_foreground = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int ic_mvvmcross_logo = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int splash_screen = 2130903042;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int MainView = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int ResearchView = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_round = 2131034113;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int app_message = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int app_welcome_message = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int AppTheme_Base = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int AppTheme_Splash = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int AppTheme_Splash_Base = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
